### ISSUE TITLE
Ramps fd v2.1

### ISSUE THREAD

**Issue by aboly8000** [bobc/KiAutotext#4]
Hello
First of all, I apologize. Because I didn't know where to ask my questions, I chose here.
In RAMPS fd v2.1 circuit, the values of resistors R701, R702, R703, R704, R901, R902, 220 ohms are stated. Are these values correct? Isn't 220 ohms too much for Gate MOSFETs?
My next question is, can I use irl3713 or FDP038AN06A0 instead of irlb8743? If so, how much should I change the gate resistance values?

**Comment by bobc** [comment]
Sorry, I am not able to provide support for RAMPS-FD, nor general electronics questions.
